### ISSUE TITLE
Update Konten FAQ to Web

### ISSUE THREAD

**Issue by aryulianto** [openinfraid/web-openinfra-id#40]
Bisa cek disini https://docs.google.com/document/d/1MF9X4PonoM7q-cCd-yWigOUnC1P2CbUEjjWQIvC5YJg/edit?usp=sharing

**Comment by aryulianto** [comment]
mas @pahrialms minta tolong yg EN dan ID udah lengkap dan bisa dinaikin

**Comment by pahrialms** [comment]
Sudah di up mas @aryulianto, tinggal di verify
